# attr = ["swinging", "adult", "attached", "bald", "delicious", "existing", "fancy", "for sale", "full", "messy", "outstretched", "posing", "rough", "nice", "beautiful", "cute", "smooth", "soft", "stacked", "wii", "outdoors", "outdoor", "light skinned", "fuzzy", "behind", "kids", "present", "hardwood", "here", "on", "concrete", "one", "thick", "part", "calm", "looking", "paved", "back", "watching", "in the picture", "three", "side", "growing", "bent", "up", "spotted", "folded", "pointy", "in background", "high", "fresh", "down", "off", "pair", "background", "some", "chain link", "top", "patterned", "waiting", "cardboard", "pointed", "four", "many", "reflective", "american", "roman", "extended", "rear", "several", "overhead", "double decker", "group", "grouped", "reflecting", "resting", "dark colored", "written", "above", "double", "glowing", "nike", "together", "row", "inside", "bunch", "plain", "fake", "ready", "pointing", "reflected", "patch", "hard", "number", "potted", "alone", "out", "stopped", "out", "partial", "set", "in the background", "single", "modern", "in the air", "in air", "mounted", "pile", "rolled", "still", "hot", "wispy", "under", "slanted", "patchy", "cell", "different", "used", "half", "transparent", "license", "head", "upright", "middle", "whole", "two", "backwards", "rolled up", "person", "cold", "staring", "reflection"]
#
#
# attr_mapa = {"small": ["mini", "shallow", "little", "small", "tiny", "smaller"],
#              "sitting": ["sitting down", "sitting"],
#              "dry": ["dry", "dried"],
#              "decorated": ["decorated", "decorative"],
#              "cloudy": ["overcast", "cloudy"],
#              "blurry": ["blurry", "blurred"],
#              "brick": ["bricked", "brick"],
#              "electronic": ["electric", "electrical", "electronic"],
#              "grass": ["grassy", "grass"],
#              "white": ["is white", "white"],
#              "long sleeved": ["long sleeved", "long sleeve"],
#              "short sleeved": ["short sleeve", "short sleeved"],
#              "rectangle": ["rectangular", "rectangle"],
#              "navy": ["navy blue", "navy"],
#              "piece": ["piece", "slice"],
#              "round": ["rounded", "round"],
#              "laying": ["laying down", "laying"],
#              "dirty": ["dirty", "dirt"],
#              "curly": ["curled", "curly"],
#              "cream": ["cream colored", "cream"],
#              "cooking": ["cooked", "cooking"],
# "brown": ["light brown", "brown"],
# "blue": ["bright blue", "light blue", "blue", "dark blue"],
# "steel": ["stainless", "aluminum", "iron", "stainless steel", "steel", "metal", "metallic"],
# "brown": ["dark brown", "brown", "light brown"],
# "ski": ["skiing", "ski"],
# "slim": ["skinny", "slim"],
# "tile": ["tiled", "tile"],
# "blonde": ["blonde", "blond"],
# "light": ["light colored", "light"],
# "old": ["older", "old"],
# "shiny": ["shining", "shiny"],
# "pile": ["piled", "pile"],
# "multicolored": ["multi-colored", "multicolored", "multi colored"],
# "green": ["evergreen", "bright green", "light green", "dark green", "green"],
# "wood": ["wooden", "wood"],
# "kid": ["baby", "kid"],
# "snow": ["snow covered", "snowy", "snow", "snowed", "snow-covered"],
# "big": ["huge", "big", "giant", "large"],
# "open": ["opened", "open"],
# "close": ["closed", "close"],
# "rust": ["rusted", "rust"],
# "playing": ["playing tennis", "playing"],
# "slice": ["chopped", "sliced", "slice", "chop", "choppy"],
# "stone": ["rock", "stone"],
# "grey": ["light grey", "dark grey", "grey", "gray", "dark gray"],
# "far": ["in the distance", "in distance", "far", "distant"],
# "standing": ["standing up", "standing"],
# "water": ["ocean", "water", "sea"],
# "fill": ["filled", "fill"],
# "drinking": ["drinking", "drink"],
# "fade": ["faded", "fade"],
# "smiling": ["smiling", "smile"],
# "human": ["person's", "human"],
# "bare": ["barefoot", "barefeet", "bare"],
# "curved": ["bending", "curved"],
# "crack": ["cracked", "crack"],
# "parked": ["parked", "parking"],
# "snowboard": ["snowboarding", "snowboard"],
# "beautyful": ["pretty", "beautiful", "beautyful", "beautyfull"],
# "lit": ["lit up", "lit"],
# "yellow": ["bright yellow", "yellow"],
# "falling": ["falling", "fall", "falled", "fallen"],
# "color": ["stained", "colored", "colorful", "color"],
# "cat": ["cat's", "cat"],
# "gold": ["golden", "gold"],
# "cotton": ["cotton", "denim"],
# "held": ["held", "holding"],
# "design": ["design", "designed"],
# "man": ["man's", "male", "man", "men", "boy's", "boy"],
# "women": ["woman's", "women's", "female", "woman", "girl's", "girl"],
# "giraffe": ["giraffe's", "giraffe"]}
#
# obj_ = ["bananas", "bricks", "children", "curtains", "doorway", "ears", "eyes", "horns", "lights", "picture frame", "poles",
# "print", "reflection", "shoes", "shutters", "stand", "tag", "tree trunk", "uniform", "vehicle", "waves", "windows",
# "zebras", "yellow line", "cables", "cable", "metal", "cart", "controller", "line", "stripe", "spot", "number", "letter",
# "letters", "top", "lines", "writing", "stripes", "cabinet", "lettering", "tracks", "lid", "branch", "wheels", "socks",
#  "object", "trim", "wing", "cord", "cloth", "word", "gloves", "wire", "area", "background", "spots", "boots",
#  "base", "branches", "cars", "sneakers", "band", "hands", "this", "awning", "wood", "doors", "stem", "track",
#  "label", "words", "outfit", "signs", "blinds", "remote", "feathers", "chairs", "dot", "shade", "text", "cabinets",
#  "wires", "structure", "clothes", "panel", "crust", "edge", "rack", "court", "walkway", "pattern", "outlet", "jet",
#  "holder", "case", "scene", "path", "symbol", "whisker", "whiskers", "mark", "clothing", "tip", "clothing", "walls",
#  "part", "pillows", "border", "carrots", "hole", "plates", "vegetables", "buttons", "signal", "weeds", "arms",
#  "elephants", "log", "white line", "handles", "step", "room", "barrier", "bin", "cows", "bun", "vegetation",
#  "name", "birds", "canopy", "tarp", "toilet seat", "ripples", "giraffes", "umpire", "visor", "towels", "apples",
#  "beam", "comforter", "body", "numeral", "piece", "countertop", "horses", "umbrellas", "concrete", "counter top",
#  "slat", "animals", "item", "pad", "slice", "bottom", "meter", "roman numeral", "front", "forest", "chest",
#  "wings", "rod", "bars", "bottles", "posts", "boats", "flags", "sheets", "group", "tires", "dresser", "paws",
#  "white letter", "couple", "onions", "snout", "screw", "drain", "marking", "knobs", "markings", "utensil",
#  "dispenser", "tomatoes", "urinal", "cleats", "kites", "hay", "oranges", "donuts", "drawers", "section",
#  "plank", "sandals", "cups", "peppers", "machine", "fixture", "sleeves", "topping", "bags", "home plate",
#  "trunks", "pant", "dots", "hinge", "shelves", "tusks", "lamp shade", "short", "belly", "roll", "image",
#  "cleat", "sprinkle", "light fixture", "pile", "cement", "vehicles", "papers", "game", "side", "bears", "tiles",
#  "gear", "grate", "players", "potatoes", "asphalt", "lampshade", "toilet bowl", "placemat", "reflector",
#  "land", "tube", "lot", "red light", "marker", "hooves", "support", "cupboard", "tennis shoes", "planes",
#  "remote control", "device", "ledge", "day", "park", "marks", "containers", "straps", "benches", "harness",
#  "napkins", "grapes", "numerals", "wool", "pipes", "sprinkles", "cords", "fingers", "light switch", "corner",
#   "candles", "plastic", "figure", "magnet", "platter", "white lines", "brown spot", "stems", "spectators",
#   "wallpaper", "end", "parking lot", "landscape", "knees", "fender", "nightstand", "archway", "station", "bark",
#   "art", "buckle", "fries", "landing gear", "rider", "petals", "wrapper", "equipment", "shirts", "jug", "material",
#   "pictures", "eggs", "sticks", "fin", "strings", "drapes", "it", "power lines", "buses", "covering", "motorcycles",
#   "fruits", "slab", "white", "claws", "color", "menu", "blind", "bikes", "bowls", "bookcase", "french fry",
#   "shadows", "tarmac", "slats", "stack", "roses", "toilet lid", "ski pants", "door knob", "shape", "baseboard",
#   "muzzle", "utensils", "columns", "power line", "bracket", "patches", "wagon - train car", "bunch", "numbers",
#  "spoke", "toppings", "panels", "boys", "island", "center", "stump", "shed", "notebook", "divider", "knee pad",
#  "ski poles", "black", "r", "n", "pathway", "package", "kids", "pots", "stroller", "sunlight", "row", "women",
#  "bikini", "books", "beans", "boxes", "buildings", "bristles", "counter", "design", "fabric", "flowers", "frame",
# "houses", "items", "people", "ribbon", "rim", "seats", "siding", "steps", "string", "surface", "trail", "trees", "shoes"]
#
#
# obj_mapa_my = {
#     "water": ["ocean", "sea", "water", "lake", "pond", "liquid"],
#     "handle": ["door handle", "handle"],
#     "hydrant": ["hydrant", "fire hydrant"],
#     "mountain": ["mountain", "mountains"],
#     "olive": ["olive", "olives"],
#     "bike": ["bicycle", "bike"],
#     "child": ["child", "kid"],
#     "racket": ["racket", "racquet"],
#     "statue": ["statue", "sculpture"],
#     "poster": ["poster", "banner", "bilboard"],
#     "logo": ["logo", "emblem"],
#     "couch": ["couch", "sofa"],
#     "donut": ["doughnut", "donut"],
# "shoe": ["shoe", "sneaker"],
# "railing": ["railing", "rail", "railings", "rail", "railing"],
# "tablecloth": ["table cloth", "tablecloth"],
# "leg": ["leg", "legs"],
# "sky": ["blue sky", "sky"],
# "belt": ["strap", "belt"],
# "clouds": ["white clouds", "clouds", "cloud", "white cloud", "cloudy sky"],
# "woman": ["lady", "woman", "girl"],
# "pavement": ["pavement", "sidewalk"],
# "cup": ["coffee cup", "mug", "cup", "coffee mug"],
# "tv": ["television", "tv"],
# "people": ["men", "people"],
# "oven": ["oven", "stove"],
# "man": ["guy", "guy", "man"],
# "pillow": ["cushion", "pillow"],
# "pot": ["jar", "pot"],
# "phone": ["cell phone", "telephone", "phone", "cellphone"],
# "shirt": ["black shirt", "red shirt", "blue shirt", "green shirt", "white shirt", "shirt"],
# "painting": ["painting", "paint", "drawing", "artwork"],
# "ski": ["ski", "skis", "skies"],
# "tree": ["palm tree", "palm tree", "green tree", "tree", "trees"],
# "glove": ["mitt", "glove"],
# "jeans": ["blue jeans", "jeans"],
# "grass": ["lawn", "green grass", "grass"],
# "shoe": ["tennis shoe", "shoe"],
# "wetsuit": ["wet suit", "wetsuit", "swimsuit"],
# "fence": ["fencing", "fence"],
# "strip": ["strip", "stripe"],
# "feathers": ["feathers", "feather"],
# "plant": ["planter", "plant", "plants"],
# "floor": ["flooring", "floor"],
# "bathtub": ["bathtub", "tub"],
# "box": ["crate", "box"],
# "hill": ["slope", "hill", "hills", "hillside", "mound"],
# "leaves": ["green leaves", "foliage", "leaves", "leafs"],
# "plate": ["white plate", "plate"],
# "hot dog": ["hot dog", "hotdog"],
# "tshirt": ["t shirt", "tank top", "tee shirt", "tshirt", "tshirt", "t-shirt"],
# "wristband": ["wrist band", "wristband"],
# "stone": ["stones", "boulder", "stone", "rock", "rocks"],
# "cap": ["baseball cap", "cap"],
# "traffic light": ["stoplight", "stop light", "traffic signal", "traffic lights", "traffic light"],
# "key": ["keys", "key"],
# "table": ["coffee table", "table top", "wooden table", "table"],
# "train car": ["train track", "train tracks", "train car"],
# "bread": ["pane", "bread"],
# "trash can": ["garbage can", "trashcan", "trash can"],
# "monitor": ["screen", "display", "monitor", "computer monitor"],
# "headlight": ["tail light", "headlights", "headlight"],
# "bush": ["shrubs", "shrub", "bushes", "bush"],
# "glass": ["wine glass", "glass"],
# "lamp post": ["light post", "streetlight", "street light", "street lamp", "lamp post", "light pole", "light post", "lamp post"],
# "shore": ["shore", "coast"],
# "rail": ["rails", "rail"],
# "animal": ["stuffed animal", "animal"],
# "post": ["fence post", "post"],
# "lips": ["lips", "lip"],
# "car": ["sedan", "car"],
# "tree": ["pine tree", "green tree", "tree"],
# "motorbike": ["scooter", "motorbike", "motorcycle"],
# "surfboard": ["surf board", "surfboard"],
# "clock": ["clock face", "clock tower", "clock"],
# "traffic sign": ["traffic sign", "street sign"],
# "bottle": ["water bottle", "bottle"],
# "pants": ["black pants", "pants"],
# "wall": ["white wall", "brick wall", "wall"],
# "man": ["male", "man"],
# "window": ["glass window", "window"],
# "pole": ["metal pole", "pole"],
# "hair": ["blonde hair", "brown hair", "black hair", "hair"],
# "bag": ["handbag", "bag"],
# "shelf": ["bookshelf", "shelf"],
# "eyeglasses": ["glasses", "eyeglasses", "goggles"],
# "nail": ["fingernail", "nail"],
# "hat": ["beanie", "hat"],
# "stairs": ["staircase", "stairs", "stair"],
# "plane": ["airplane", "aircraft", "plane"],
# "boat": ["sailboat", "boat"],
# "door": ["cabinet door", "door"],
# "leaf": ["green leaf", "leaf"],
# "branch": ["tree branch", "branch"],
# "sign": ["white sign", "sign"],
# "food": ["meal", "food"],
# "building": ["brick building", "building", "house"],
# "tie": ["bow tie", "necktie", "tie"],
# "store": ["store", "supermarket"],
# "train": ["train engine", "train"],
# "teeth": ["tooth", "teeth"],
# "road": ["roadway", "road"],
# "ground": ["soil", "ground"],
# "cat": ["kitten", "cat"],
# "trees": ["green trees", "trees"],
# "girl": ["little girl", "girl"],
# "cone": ["traffic cone", "cone"],
# "beach": ["beach", "sand"]
# }
